stages:
- maven
- docker
- release

cache:
  untracked: true
  key: "auth-m2"
  paths:
  - m2

build-jar:
  stage: maven
  image: harbor.rand0m.me/public/centos8-base:latest
  tags:
  - docker
  script:
  - sh scripts/build-maven.sh
  only:
  - master
  artifacts:
    paths:
    - auth-app/target/auth-app.jar
    expire_in: 20 mins

build-image-amd64:
  stage: docker
  image: docker
  only:
  - master
  tags:
  - docker
  script:
  - sh scripts/build-docker.sh

build-image-aarch64:
  stage: docker
  image: docker
  only:
  - master
  tags:
  - docker-aarch64
  script:
  - sh scripts/build-docker.sh

release:
  stage: release
  image: harbor.rand0m.me/public/centos8-base:latest
  tags:
  - docker
  script:
  - sh scripts/release.sh
  only:
  - master
  when: manual
