apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-service
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 8080
    protocol: "TCP"
  selector:
    app: "auth-app"
    release: {{ .Release.Name | quote}}
