server.servlet.contextPath: /
spring.resources.cache.period: 1
spring.thymeleaf.cache: false
security.basic.enabled: false
host: "${PROTO:http://}${HOST:127.0.0.1}:8080/"
spring.mvc.static-path-pattern: /**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
zuul:
  ignoredHeaders: []
  ignoredPatterns:
   - /__auth__/**
  sensitiveHeaders: []
  host.socket-timeout-millis: 60000
  routes:
    static:
      path: /**
      url: "${BACKEND_URL:http://192.168.71.220:8096}/"
web-ldap:
  enabled: true
  baseUrl: https://users.rand0m.me
  groupIds:
  - a617a78c-a179-40cf-b7a6-e4c6f11b8160
bearer-token:
  enabled: true
  allow:
  - banana  