FROM harbor.rand0m.me/public/springboot:latest
MAINTAINER Ruben Malchow <ruben.malchow@mcon-group.com>
COPY vrtlr-app/target/vrtlr-app.jar vrtlr-app.jar
COPY vrtlr-app/config/application.yml ./
#CMD [ "-j" , "shrtnr-app.jar", "-o", "-Xmx512m" ]
