server.servlet.contextPath: /
spring.resources.cache.period: 1
spring.thymeleaf.cache: true
security.basic.enabled: false
host: "{{ .Values.ingress.proto | default "https" }}://{{ .Values.ingress.host }}/"
spring.mvc.static-path-pattern: /**
spring.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
zuul:
  ignoredHeaders: []
  ignoredPatterns:
   - /__auth__/**
  sensitiveHeaders: []
  host.socket-timeout-millis: 60000
  routes:
    static:
      path: /**
      url: "http://{{ .Values.backend.servicename}}:{{ .Values.backend.port}}"
{{ toYaml .Values.auth  }}
